---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci

  stage-files:
    image: rancher/dapper:1.11.2
    commands:
    - cp -r ./bin/* ./package/
    - cp -rp ./img ./package/
    when:
      branch: master
      event: tag

  publish-image:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: rancher/hello-world
    context: package/
    tag: 
    - ${DRONE_TAG}
    - latest
    secrets: [docker_username, docker_password]
    build_args:
    - VERSION=${DRONE_TAG}
    when:
      branch: master
      event: tag

